# 4.1 Exercise on Functions:

In [ ]:
#Task - 1:

def convert_units(conversion_type, value):
    """
    Converts a value to different measurement.

    Parameters:
    conversion_type (str): The type of conversion to perform.
                           Options:
                           - 'm_to_ft'
                           - 'ft_to_m'
                           - 'kg_to_lbs'
                           - 'lbs_to_kg'
                           - 'l_to_gal'
                           - 'gal_to_l'
    value (float): The numeric value to convert.

    Returns:
    float: Value converted.
    """

    if conversion_type == "m_to_ft":
        return value * 3.28084
    elif conversion_type == "ft_to_m":
        return value / 3.28084
    elif conversion_type == "kg_to_lbs":
        return value * 2.20462
    elif conversion_type == "lbs_to_kg":
        return value / 2.20462
    elif conversion_type == "l_to_gal":
        return value * 0.264172
    elif conversion_type == "gal_to_l":
        return value / 0.264172
    else:
        raise ValueError("Unsupported conversion type.")


def main():
    print("Unit Conversion Program")
    print("-----------------------")
    print("Choose conversion type:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    choice = input("Enter your choice (1/2/3): ")

    try:
        if choice == "1":
            print("\nLength Conversions:")
            print("1. Meters to Feet")
            print("2. Feet to Meters")
            sub_choice = input("Enter your choice (1/2): ")

            value = float(input("Enter the value to convert: "))

            if sub_choice == "1":
                result = convert_units("m_to_ft", value)
                print(f"{value} meters = {result:.4f} feet")
            elif sub_choice == "2":
                result = convert_units("ft_to_m", value)
                print(f"{value} feet = {result:.4f} meters")
            else:
                print("Invalid length conversion choice.")

        elif choice == "2":
            print("\nWeight Conversions:")
            print("1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            sub_choice = input("Enter your choice (1/2): ")

            value = float(input("Enter the value to convert: "))

            if sub_choice == "1":
                result = convert_units("kg_to_lbs", value)
                print(f"{value} kg = {result:.4f} lbs")
            elif sub_choice == "2":
                result = convert_units("lbs_to_kg", value)
                print(f"{value} lbs = {result:.4f} kg")
            else:
                print("Invalid weight conversion choice.")

        elif choice == "3":
            print("\nVolume Conversions:")
            print("1. Liters to Gallons")
            print("2. Gallons to Liters")
            sub_choice = input("Enter your choice (1/2): ")

            value = float(input("Enter the value to convert: "))

            if sub_choice == "1":
                result = convert_units("l_to_gal", value)
                print(f"{value} liters = {result:.4f} gallons")
            elif sub_choice == "2":
                result = convert_units("gal_to_l", value)
                print(f"{value} gallons = {result:.4f} liters")
            else:
                print("Invalid volume conversion choice.")

        else:
            print("Invalid main choice. Please select 1, 2, or 3.")

    except ValueError:
        print("Error: Please enter a valid numeric value.")


if __name__ == "__main__":
    main()

Unit Conversion Program
-----------------------
Choose conversion type:
1. Length
2. Weight
3. Volume
Enter your choice (1/2/3): 2

Weight Conversions:
1. Kilograms to Pounds
2. Pounds to Kilograms
Enter your choice (1/2): 1
Enter the value to convert: 65.8
65.8 kg = 145.0640 lbs


In [ ]:
#task 2

def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The sum of the numbers.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The average of the numbers.

    Raises:
    ValueError: If the list is empty.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot calculate average of an empty list.")
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    """
    Finds the maximum value in a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The maximum number.

    Raises:
    ValueError: If the list is empty.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find maximum of an empty list.")
    return max(numbers)


def find_minimum(numbers):
    """
    Finds the minimum value in a list of numbers.

    Parameters:
    numbers (list of float): The list of numbers.

    Returns:
    float: The minimum number.

    Raises:
    ValueError: If the list is empty.
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find minimum of an empty list.")
    return min(numbers)


def main():
    print("Mathematical Operations on a List")
    print("---------------------------------")
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter your choice (1/2/3/4): ")

    try:
        user_input = input("Enter numbers separated by spaces: ").strip()

        if not user_input:
            raise ValueError("Input list cannot be empty.")

        numbers = [float(num) for num in user_input.split()]

        if choice == "1":
            result = calculate_sum(numbers)
            print(f"Sum = {result}")

        elif choice == "2":
            result = calculate_average(numbers)
            print(f"Average = {result}")

        elif choice == "3":
            result = find_maximum(numbers)
            print(f"Maximum = {result}")

        elif choice == "4":
            result = find_minimum(numbers)
            print(f"Minimum = {result}")

        else:
            print("Invalid operation choice.")

    except ValueError as e:
        print(f"Error: {e}")


if __name__ == "__main__":
    main()

Mathematical Operations on a List
---------------------------------
Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter your choice (1/2/3/4): 2
Enter numbers separated by spaces: 100 200 300 400 500
Average = 300.0


# 4.2 Exercise on List Manipulation:

In [ ]:
#task 1
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.

    Parameters:
    lst (list): The input list.

    Returns:
    list: A new list containing every other element from the original list.
    """
    return lst[::2]


def main():
    try:
        user_input = input("Enter elements separated by spaces: ").strip()

        elements = user_input.split()

        result = extract_every_other(elements)

        print("Every other element:", result)

    except Exception as e:
        print("Error:", e)


if __name__ == "__main__":
    main()

Enter elements separated by spaces: 10 20 30 40 50
Every other element: ['10', '30', '50']


In [ ]:
#task 2
def get_sublist(lst, start, end):
    """
    Returns a sublist from the given list between the specified start and end indices (inclusive).

    Parameters:
    lst (list): The original list.
    start (int): The starting index.
    end (int): The ending index (inclusive).

    Returns:
    list: A sublist from index start to end.

    Raises:
    ValueError: If indices are invalid.
    """
    if start < 0 or end >= len(lst):
        raise ValueError("Start or end index is out of range.")
    if start > end:
        raise ValueError("Start index cannot be greater than end index.")

    return lst[start:end + 1]


def main():
    try:
        user_input = input("Enter elements separated by spaces: ").strip()

        if not user_input:
            raise ValueError("Input list cannot be empty.")

        lst = user_input.split()

        start = int(input("Enter start index: "))
        end = int(input("Enter end index: "))

        result = get_sublist(lst, start, end)

        print("Sublist:", result)

    except ValueError as e:
        print("Error:", e)


if __name__ == "__main__":
    main()

Enter elements separated by spaces: 1 2 3 4 5 6
Enter start index: 2
Enter end index: 4
Sublist: ['3', '4', '5']


In [ ]:
#task 3
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list with elements in reverse order.
    """
    return lst[::-1]


example = [1, 2, 3, 4, 5]
result = reverse_list(example)
print(result)

[5, 4, 3, 2, 1]


In [ ]:
#task 4
def remove_first_last(lst):
    """
    Removes the first and last elements of a list.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list without the first and last elements.

    Raises:
    ValueError: If the list has fewer than 2 elements.
    """
    if len(lst) < 2:
        raise ValueError("List must contain at least two elements.")

    return lst[1:-1]


example = [1, 2, 3, 4, 5]
result = remove_first_last(example)
print(result)

[2, 3, 4]


In [ ]:
#task 5
def get_first_n(lst, n):
    """
    Returns the first n elements from a list using slicing.

    Parameters:
    lst (list): The original list.
    n (int): Number of elements to extract.

    Returns:
    list: A new list containing the first n elements.

    Raises:
    ValueError: If n is negative.
    """
    if n < 0:
        raise ValueError("n cannot be negative.")

    return lst[:n]


example = [1, 2, 3, 4, 5]
result = get_first_n(example, 3)
print(result)

[1, 2, 3]


In [ ]:
#task 6
def get_last_n(lst, n):
    """
    Returns the last n elements from a list using slicing.

    Parameters:
    lst (list): The original list.
    n (int): Number of elements to extract from the end.

    Returns:
    list: A new list containing the last n elements.

    Raises:
    ValueError: If n is negative.
    """
    if n < 0:
        raise ValueError("n cannot be negative.")

    return lst[-n:] if n != 0 else []


example = [1, 2, 3, 4, 5]
result = get_last_n(example, 2)
print(result)

[4, 5]


In [ ]:
#task 7
def reverse_skip(lst):
    """
    Extracts every second element from a list in reverse order,
    starting from the second-to-last element.

    Parameters:
    lst (list): The original list.

    Returns:
    list: A new list containing every second element from the end,
          starting from the second-to-last element.
    """
    return lst[-2::-2]


example = [1, 2, 3, 4, 5, 6]
result = reverse_skip(example)
print(result)

[5, 3, 1]


# 4.3 Exercise on Nested List

In [ ]:
#task 1
def flatten(lst):
    """
    Flattens a nested list into a single-dimensional list.

    Parameters:
    lst (list): The input nested list.

    Returns:
    list: A flattened list containing all elements in a single dimension.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(flatten(item))
        else:
            flat_list.append(item)
    return flat_list


nested_list = [[1, 2], [3, 4], [5]]
result = flatten(nested_list)
print(result)

[1, 2, 3, 4, 5]


In [ ]:
#task 2
def access_nested_element(lst, indices):
    """
    Accesses an element in a nested list given a list of indices.

    Parameters:
    lst (list): The nested list.
    indices (list of int): List of indices representing the path to the element.

    Returns:
    any: The element at the specified indices.

    Raises:
    IndexError: If any index is out of range.
    TypeError: If the accessed element is not a list when expecting more indices.
    """
    element = lst
    for idx in indices:
        if not isinstance(element, list):
            raise TypeError(f"Expected a list at index {idx}, but got {type(element).__name__}")
        element = element[idx]
    return element


nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)
print(result)

6


In [ ]:
#task 3
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list (any depth).

    Parameters:
    lst (list): The input nested list containing numbers or other nested lists.

    Returns:
    int/float: The sum of all elements in the nested list.
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested_list)
print(result)

21


In [ ]:
#task 4
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): The input nested list.
    elem (any): The element to remove.

    Returns:
    list: A new nested list with all occurrences of elem removed.
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

nested_list = [[1, 2], [3, 2], [4, 5]]
elem_to_remove = 2
result = remove_element(nested_list, elem_to_remove)
print(result)

[[1], [3], [4, 5]]


In [ ]:
#task 5
def find_max(lst):
    """
    Finds the maximum element in a nested list (any depth).

    Parameters:
    lst (list): The input nested list containing numbers or other nested lists.

    Returns:
    int/float: The maximum element in the nested list.
    """
    max_val = float('-inf')

    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)

    return max_val


nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)
print(result)

6


In [ ]:
#task 6
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
    lst (list): The input nested list.
    elem (any): The element to count.

    Returns:
    int: The number of times elem appears in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count


nested_list = [[1, 2], [2, 3], [2, 4]]
elem_to_count = 2
result = count_occurrences(nested_list, elem_to_count)
print(result)

3


In [ ]:
#task 7
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list.

    Parameters:
    lst (list): The input nested list of any depth.

    Returns:
    list: A new flattened list containing all elements in a single dimension.
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list


nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
#task 8
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list (any depth).

    Parameters:
    lst (list): The input nested list containing numbers or other nested lists.

    Returns:
    float: The average of all elements in the nested list.
    """
    def helper(sublist):
        """
        Returns the sum and count of elements in a nested list.
        """
        total = 0
        count = 0
        for item in sublist:
            if isinstance(item, list):
                sub_total, sub_count = helper(item)
                total += sub_total
                count += sub_count
            else:
                total += item
                count += 1
        return total, count

    total_sum, total_count = helper(lst)
    if total_count == 0:
        raise ValueError("Cannot calculate average of an empty list.")
    return total_sum / total_count


nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)
print(result)

3.5


# 10.1 Basic Vector and Matrix Operation with Numpy.

In [28]:
import numpy as np

In [30]:
# Task 1
zeros_array = np.zeros((2, 2))
print("Zeros 2x2:\n", zeros_array)

ones_array = np.ones((4, 2))
print("\nAll-one 4x2 array:\n", ones_array)

fill_value_array = np.full((3, 3), fill_value=7, dtype=int)
print("\nArray filled with 7:\n", fill_value_array)

sample_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(sample_array)
print("\nZeros like sample array:\n", zeros_like_array)

ones_like_array = np.ones_like(sample_array)
print("\nOnes like sample array:\n", ones_like_array)

new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\nArray from list:\n", array_from_list)

Zeros 2x2:
 [[0. 0.]
 [0. 0.]]

All-one 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like sample array:
 [[0 0 0]
 [0 0 0]]

Ones like sample array:
 [[1 1 1]
 [1 1 1]]

Array from list:
 [1 2 3 4]


In [31]:
# task 2
range_array = np.arange(10, 50)
print("\nArray from 10 to 49:\n", range_array)

matrix_3x3 = np.arange(9).reshape((3, 3))
print("\n3x3 matrix 0-8:\n", matrix_3x3)

identity_matrix = np.eye(3)
print("\n3x3 Identity matrix:\n", identity_matrix)

random_array_30 = np.random.random(30)
mean_value = random_array_30.mean()
print("\nRandom array size 30:\n", random_array_30)
print("Mean of array:", mean_value)

random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print("\n10x10 random array:\n", random_10x10)
print("Min:", min_val, "Max:", max_val)

zero_array_10 = np.zeros(10)
zero_array_10[4] = 1
print("\nZero array with 5th element as 1:\n", zero_array_10)

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:\n", reversed_arr)

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on border, 0 inside:\n", border_array)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard pattern:\n", checkerboard)


Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix 0-8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array size 30:
 [0.47890607 0.04577291 0.39867864 0.90839757 0.38704343 0.67242965
 0.11892573 0.41427546 0.23001856 0.31418829 0.45562396 0.8567961
 0.4828567  0.73943808 0.54336836 0.18858822 0.71842255 0.35263175
 0.97558734 0.40072407 0.97717305 0.28097386 0.87528981 0.54872531
 0.34386528 0.49755933 0.10567185 0.50952734 0.28884245 0.99149821]
Mean of array: 0.5033933309348175

10x10 random array:
 [[0.20632315 0.90310914 0.78325722 0.73990716 0.69582859 0.90915165
  0.29240602 0.77706318 0.60353877 0.15423937]
 [0.54340724 0.25202233 0.09494432 0.63581645 0.25098901 0.87943808
  0.61583348 0.05239772 0.85894617 0.54475807]
 [0.57886422 0.46177184 0.3013303  0.10560865 0.22681915 0.88131643
  0.47531055 0.85584977 0.14735529 

In [32]:
# task 3
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add_xy = x + y
print("x + y:\n", add_xy)

sub_xy = x - y
print("\nx - y:\n", sub_xy)

mul_x = x * 3
print("\nx * 3:\n", mul_x)

square_x = x**2
print("\nx squared:\n", square_x)

dot_vw = np.dot(v, w)
print("\nDot product of v and w:", dot_vw)

dot_xv = np.dot(x, v)
print("Dot product of x and v:\n", dot_xv)

dot_xy = np.dot(x, y)
print("Dot product of x and y:\n", dot_xy)

concat_xy_row = np.concatenate((x, y), axis=0)
print("\nConcatenate x and y along rows:\n", concat_xy_row)

concat_vw_col = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)
print("\nConcatenate v and w along columns:\n", concat_vw_col)

try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\nError concatenating x and v:", e)
    print("Explanation: x is 2x2 and v is 1D array of length 2; shapes do not match along axis 1.")

x + y:
 [[ 6  8]
 [10 13]]

x - y:
 [[-4 -4]
 [-4 -3]]

x * 3:
 [[ 3  6]
 [ 9 15]]

x squared:
 [[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

Error concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is 2x2 and v is 1D array of length 2; shapes do not match along axis 1.


In [33]:
# task 4 matrix operation
A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])

A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A^-1:\n", identity)

print("Is identity:", np.allclose(identity, np.eye(2)))

AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))

AB_T = (np.dot(A, B)).T
B_TA_T = np.dot(B.T, A.T)
print("\n(AB)^T:\n", AB_T)
print("B^T * A^T:\n", B_TA_T)
print("Are they equal?", np.array_equal(AB_T, B_TA_T))

A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is identity: True

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Are AB and BA equal? False

(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Are they equal? True


In [35]:
# task 4 linear equations
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])

B_eq = np.array([-1, -3, 9])

X_solve = np.linalg.solve(A_eq, B_eq)
print("\nSolution using np.linalg.solve:", X_solve)

X_inv = np.dot(np.linalg.inv(A_eq), B_eq)
print("Solution using np.linalg.inv:", X_inv)


Solution using np.linalg.solve: [ 2.  1. -2.]
Solution using np.linalg.inv: [ 2.  1. -2.]


# 10.2 Experiment: How Fast is Numpy?

In [40]:
import time

In [41]:
# Task 1
size = 1_000_000

list1 = list(range(size))
list2 = list(range(size))

start_time = time.time()
py_add = [a + b for a, b in zip(list1, list2)]
end_time = time.time()
print("Python list addition time:", end_time - start_time, "seconds")

arr1 = np.arange(size)
arr2 = np.arange(size)

start_time = time.time()
np_add = arr1 + arr2
end_time = time.time()
print("NumPy array addition time:", end_time - start_time, "seconds")


Python list addition time: 0.07242798805236816 seconds
NumPy array addition time: 0.004935741424560547 seconds


In [42]:
# task 2
start_time = time.time()
py_mul = [a * b for a, b in zip(list1, list2)]
end_time = time.time()
print("\nPython list multiplication time:", end_time - start_time, "seconds")

start_time = time.time()
np_mul = arr1 * arr2
end_time = time.time()
print("NumPy array multiplication time:", end_time - start_time, "seconds")


Python list multiplication time: 0.14253616333007812 seconds
NumPy array multiplication time: 0.003485441207885742 seconds


In [43]:
#task 3
start_time = time.time()
py_dot = sum(a * b for a, b in zip(list1, list2))
end_time = time.time()
print("\nPython list dot product time:", end_time - start_time, "seconds")

start_time = time.time()
np_dot = np.dot(arr1, arr2)
end_time = time.time()
print("NumPy array dot product time:", end_time - start_time, "seconds")


Python list dot product time: 0.10060501098632812 seconds
NumPy array dot product time: 0.002155780792236328 seconds


In [46]:
#task 4
mat_size = 1000

py_mat1 = [[i + j for j in range(mat_size)] for i in range(mat_size)]
py_mat2 = [[i - j for j in range(mat_size)] for i in range(mat_size)]

start_time = time.time()
py_result = [[sum(py_mat1[i][k] * py_mat2[k][j] for k in range(mat_size))
              for j in range(mat_size)] for i in range(mat_size)]
end_time = time.time()
print("\nPython list matrix multiplication time:", end_time - start_time, "seconds")

np_mat1 = np.arange(mat_size**2).reshape(mat_size, mat_size)
np_mat2 = np.arange(mat_size**2).reshape(mat_size, mat_size)

start_time = time.time()
np_result = np.dot(np_mat1, np_mat2)
end_time = time.time()
print("NumPy array matrix multiplication time:", end_time - start_time, "seconds")


Python list matrix multiplication time: 180.51721477508545 seconds
NumPy array matrix multiplication time: 2.0885989665985107 seconds
